version: '3.7'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_DB: test
      POSTGRES_PASSWORD: test
    volumes:
      - postgres_screening:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  postgres_screening:
    external: true
